### ISSUE TITLE
Hexadecimal string generation. Stage : `early`

### ISSUE THREAD

**Issue by volodymyrmigdal** [Learn-Together-Pro/Blockchain#10]
*Complexity* : **difficult**
*Stage* : **early**

Implement method `bytes_to_string_hex` for `Digest`. 

```rs
pub fn bytes_to_string_hex(  src : &[ u8 ] ) -> String
```

Method accepts a bytes array and returns converted hexadecimal string.

**Comment by TheBestTvarynka** [comment]
Mine

**Comment by TheBestTvarynka** [comment]
#24
