### ISSUE TITLE
Command `.system.difficulty`. Stage : `early`

### ISSUE THREAD

**Issue by volodymyrmigdal** [Learn-Together-Pro/Blockchain#15]
*Complexity* : **easy**
*Stage* : **early**

Implement command function `command_system_difficulty`  in [`main.rs`.](https://github.com/Learn-Together-Pro/Blockchain/blob/main/rust/main.rs)

```rs
fn command_system_difficulty( _sys : &mut System )
```

Function changes a [`difficulty`](https://en.bitcoin.it/wiki/Difficulty) of mining.

Function should:
- Generate a input prompt.
- Ask user to enter value ( String -> u32 ).
- Update field `difficulty` of the chain.
- Store system into a file.

Optional ( good practice ) : 
- Limit the maximal `difficulty` of the system to prevent infinite loop.

**Comment by DrewFrost** [comment]
I'll take
