### ISSUE TITLE
Enable persistence of data ( for a teamlead ). Stage : `mid`

### ISSUE THREAD

**Issue by Wandalen** [Learn-Together-Pro/Blockchain#21]
*Complexity* : **difficult**
*Stage* : **mid**

Preserve data from one run of the application to another. Instead of creating a new system in the main:

```rs
let mut sys = System::Make();
``` 

call System::Load(). But if System::Load() fails to load data from the file, call System::MakePersistant() that should create an empty system and save it into the file. The next time application will be launched with available data.

**Comment by GlaciErrDev** [comment]
On it
