### ISSUE TITLE
Method to ganerate pair of keys. Stage : `late`

### ISSUE THREAD

**Issue by dmvict** [Learn-Together-Pro/Blockchain#3]
*Complexity* : **mid**
*Stage* : **late**

Implement method `keys_pair_generate` for `Wallet`.

```rs
  fn keys_pair_generate() -> ( Digest, Digest )
```

Method should : 
- Generate public and private key ( algorithm - [RSA](https://en.wikipedia.org/wiki/RSA_(cryptosystem)), length - 2048 bit ).
- Convert the keys to digests.
- Return tuple of digests  in defined order `( public_key, private_key )`.

Use crate [`rsa`.](https://crates.io/crates/rsa).

**Comment by DrewFrost** [comment]
I'l try
