### ISSUE TITLE
Function to calculate merkle hash. Stage : `early`

### ISSUE THREAD

**Issue by Wandalen** [Learn-Together-Pro/Blockchain#6]
*Complexity* : **mid**
*Stage* : **early**

Implement function `merkle_calc` making a markle hash from a vector of transations. 

Implementation should collect a vector `body.hash` of each transaction and call function `hash_every` for the vector. 
 
```
pub fn merkle_calc( transactions : &Vec< Transaction > ) -> Digest
```

**Comment by bytefall** [comment]
I'll take it.
